/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import java.sql.*;

/**
 *
 * @author Yuki
 */
public class menu extends javax.swing.JFrame {
private Connection conn = new koneksi().connect();
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        setSize(510,570);
        setLocationRelativeTo(null);
        this.setResizable(false);
        setTitle("Dashboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bexit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        master = new javax.swing.JMenu();
        msiswa = new javax.swing.JMenuItem();
        mbrg = new javax.swing.JMenuItem();
        mstock = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        tpenjbrg = new javax.swing.JMenuItem();
        mbrgmsk = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon Exit.png"))); // NOI18N
        bexit.setText("Exit");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        getContentPane().add(bexit);
        bexit.setBounds(410, 450, 80, 25);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selamat Datang");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 80, 200, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Di Aplikasi Koperasi Sekolah");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 110, 360, 33);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logo_MTsN_1_Jakarta-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 510);

        master.setText("Master");
        master.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        msiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon Siswa.png"))); // NOI18N
        msiswa.setText("Data Siswa");
        msiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msiswaActionPerformed(evt);
            }
        });
        master.add(msiswa);

        mbrg.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mbrg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon Data Barang.png"))); // NOI18N
        mbrg.setText("Daftar Barang");
        mbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbrgActionPerformed(evt);
            }
        });
        master.add(mbrg);

        mstock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon Stok Barang.png"))); // NOI18N
        mstock.setText("Stock Barang");
        mstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mstockActionPerformed(evt);
            }
        });
        master.add(mstock);

        jMenuBar1.add(master);

        transaksi.setText("Transaksi");
        transaksi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tpenjbrg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon Transaksi.png"))); // NOI18N
        tpenjbrg.setText("Penjualan");
        tpenjbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpenjbrgActionPerformed(evt);
            }
        });
        transaksi.add(tpenjbrg);

        mbrgmsk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon Transaksi.png"))); // NOI18N
        mbrgmsk.setText("TR Barang Masuk");
        mbrgmsk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbrgmskActionPerformed(evt);
            }
        });
        transaksi.add(mbrgmsk);

        jMenuBar1.add(transaksi);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbrgActionPerformed
        // TODO add your handling code here:
        barang mainMenu = new barang();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mbrgActionPerformed

    private void mstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mstockActionPerformed
        // TODO add your handling code here:
         stock mainMenu = new stock();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mstockActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bexitActionPerformed

    private void tpenjbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpenjbrgActionPerformed
        // TODO add your handling code here:
        Penjualan mainMenu = new Penjualan();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tpenjbrgActionPerformed

    private void msiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msiswaActionPerformed
        // TODO add your handling code here:
        Data_Siswa mainMenu = new Data_Siswa();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_msiswaActionPerformed

    private void mbrgmskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbrgmskActionPerformed
        // TODO add your handling code here:
        Barang_Masuk mainMenu = new Barang_Masuk();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mbrgmskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu master;
    private javax.swing.JMenuItem mbrg;
    private javax.swing.JMenuItem mbrgmsk;
    private javax.swing.JMenuItem msiswa;
    private javax.swing.JMenuItem mstock;
    private javax.swing.JMenuItem tpenjbrg;
    private javax.swing.JMenu transaksi;
    // End of variables declaration//GEN-END:variables
}
